administrator_signup:
    path: /signup
    controller: App\Controller\AdministratorController::signup
administrator_signin:
    path: /signin
    controller: App\Controller\AdministratorController::signin