dashboard_top:
    path: /
    controller: App\Controller\DashboardController::top

dashboard_home:
    path: /home
    controller: App\Controller\DashboardController::home

administrator_signup:
    path: /signup
    controller: App\Controller\AdministratorController::signup

administrator_signin:
    path: /signin
    controller: App\Controller\AdministratorController::signin